#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ERDO_DIR=$(dirname $0)/../../..
CLASSPATH="$JDK_HOME/jre/lib/rt.jar:$ERDO_DIR/target/test-classes:$ERDO_DIR/target/classes"

COMMAND="java -ea -Dpid=$$ -Djava.util.logging.config.file=$ERDO_DIR/src/main/resources/testlogging.properties -Dfile.encoding=UTF-8 -classpath $CLASSPATH com.geophile.erdo.systemtest.singleprocess.ProcessExclusionTest"

$COMMAND create &
sleep 2
$COMMAND &
